### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by tiziodcaio** [dreamwhite/apci-battery-patching-guide#1]
I think it would be better if you insert an example in the 32 bit guide

**Comment by dreamwhite** [comment]
> At the end of 16 bit patching there is a missing link
> I think it would be better if you insert an example in the 32 bit guide

Wait I'm a little bit confused. May you gently provide screenshot and eventually submit a PR so we can discuss on that?

**Comment by tiziodcaio** [comment]
Ok sorry I am a bit confusing. After I attach screenshots

**Comment by tiziodcaio** [comment]
![immagine](https://user-images.githubusercontent.com/61084118/111455934-b0318e00-8716-11eb-999c-d8013692c590.png)
doest the "*" section be copied as it is or it have to be changed as your system? It is the second I think you should create an example

**Comment by tiziodcaio** [comment]
so dumb... remove the first question

**Comment by dreamwhite** [comment]
Okay I perfectly got your point. No, we don't need to edit this patch since, as you can see, this is just a shift mechanism of bits which shift bits in order to recreate the pieces of the original field, from the splitted ones.
If there aren't more doubts, don't hesitate to ask there
